const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, 'zoom_gestures.rs'),'utf8').split('indoc::indoc! {r#"')[1].split('"#}')[0];
const listeners = new Map();
const messages = [];
const listen = (name,fn)=>listeners.set(name,fn);
vm.runInNewContext(source, {document:{addEventListener:listen},window:{addEventListener:listen},dioxus:{send:value=>messages.push(JSON.parse(JSON.stringify(value)))}});
const fire = (type, data={}) => listeners.get(type)({...data,preventDefault(){},stopImmediatePropagation(){}});
fire('gesturestart',{altKey:false});
fire('gesturechange',{scale:1.4});
assert.deepEqual(messages.at(-1),{ui:false,kind:'scale',value:1.4});
fire('gestureend');
fire('keydown',{altKey:true,code:'AltLeft'});
fire('gesturestart',{altKey:false});
fire('gesturechange',{altKey:false,scale:1.2});
assert.deepEqual(messages.at(-1),{ui:true,kind:'scale',value:1.2});
fire('gestureend');
fire('keyup',{altKey:false,code:'AltLeft'});
fire('gesturestart',{altKey:false});
fire('gesturechange',{scale:1.1});
assert.equal(messages.at(-1).ui,false);
fire('gestureend');
fire('keydown',{metaKey:true,shiftKey:true,altKey:false,code:'Equal'});
assert.deepEqual(messages.at(-1),{ui:true,kind:'step',value:0.05});
fire('keydown',{metaKey:true,shiftKey:true,altKey:false,code:'Minus'});
assert.deepEqual(messages.at(-1),{ui:true,kind:'step',value:-0.05});
fire('keydown',{metaKey:true,shiftKey:true,altKey:false,code:'Digit0'});
assert.deepEqual(messages.at(-1),{ui:true,kind:'reset',value:0});
console.log('PASS: Option pinch without gesture modifiers; Cmd+Shift UI zoom at 5%');
